{{- if .Values.containerConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "test-nginx-chart.fullname" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "test-nginx-chart.fullname" . }}"
data:
{{- range $path, $config := .Values.containerConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}
